FROM ubuntu

RUN apt-get update
RUN apt-get install -y openssh-client

COPY hotstuff /usr/bin/

WORKDIR /root
ADD id .ssh/
ADD id.pub .ssh/
ADD ssh_config .ssh/config
ADD example_config.toml ./example_config.toml
